### ISSUE TITLE
plugins/vsenv.py fails under linux

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#39]
```
$ bob ls
An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Bob version 0.18.2.dev30+g5e670dc.dirty
Traceback (most recent call last):
  File "/mnt/c/bob/pym/bob/scripts.py", line 147, in catchErrors
    ret = fun(*args, **kwargs)
  File "/mnt/c/bob/pym/bob/scripts.py", line 248, in cmd
    ret = cmd(args.args, bobRoot)
  File "/mnt/c/bob/pym/bob/scripts.py", line 54, in __ls
    doLS(*args, **kwargs)
  File "/mnt/c/bob/pym/bob/cmds/misc.py", line 104, in doLS
    for (stack, root) in packages.queryTreePath(args.package):
  File "/mnt/c/bob/pym/bob/pathspec.py", line 852, in queryTreePath
    (nodes, valid) = self.__query(path)
  File "/mnt/c/bob/pym/bob/pathspec.py", line 829, in __query
    root = self.__getGraphRoot()
  File "/mnt/c/bob/pym/bob/pathspec.py", line 781, in __getGraphRoot
    self.getRootPackage)
  File "/mnt/c/bob/pym/bob/pathspec.py", line 535, in init
    root = PkgGraphNode.__convertPackageToGraph(db, rootGenerator())
  File "/mnt/c/bob/pym/bob/pathspec.py", line 843, in getRootPackage
    self.__root = self.__generator()
  File "/mnt/c/bob/pym/bob/input.py", line 3725, in <lambda>
    lambda: self.__generatePackages(nameFormatter, env, cacheKey, sandboxEnabled))
  File "/mnt/c/bob/pym/bob/input.py", line 3707, in __generatePackages
    result = self.__rootRecipe.prepare(env, sandboxEnabled, states)[0]
  File "/mnt/c/bob/pym/bob/input.py", line 2465, in prepare
    thisDepTools, depStack)
  File "/mnt/c/bob/pym/bob/input.py", line 2465, in prepare
    thisDepTools, depStack)
  File "/mnt/c/bob/pym/bob/input.py", line 2653, in prepare
    for (name, tool) in self.__provideTools.items() }
  File "/mnt/c/bob/pym/bob/input.py", line 2653, in <dictcomp>
    for (name, tool) in self.__provideTools.items() }
  File "/mnt/c/bob/pym/bob/input.py", line 548, in prepare
    for k, v in self.environment.items() }
  File "/mnt/c/bob/pym/bob/input.py", line 548, in <dictcomp>
    for k, v in self.environment.items() }
  File "/mnt/c/bob/pym/bob/stringparser.py", line 511, in substitute
    return StringParser(self, self.funs, self.funArgs, nounset).parse(value)
  File "/mnt/c/bob/pym/bob/stringparser.py", line 50, in parse
    return self.getString()
  File "/mnt/c/bob/pym/bob/stringparser.py", line 125, in getString
    s.append(self.getCommand())
  File "/mnt/c/bob/pym/bob/stringparser.py", line 202, in getCommand
    return self.funs[cmd](words, env=self.env, **self.funArgs)
  File "layers/basement/plugins/vsenv.py", line 15, in vsvars2019
    vswargs = (os.path.join(os.environ["ProgramFiles(x86)"],
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'ProgramFiles(x86)'
```

Does this just fail for me? Why, this should also fail in the basement-crossplatform-tests?!

I guess the "(" and ")" are the problem for the os environment python stuff.
I "fixed" it by adding a KeyError-exception.

**Comment by mahaase** [comment]
```
- if: !expr |
     "${BOB_HOST_PLATFORM}" == "msys" || "${BOB_HOST_PLATFORM}" == "win32"
```

solution! Okay, that is the reason, why this works for tests. should we catch the error in vsenv?

**Comment by jkloetzke** [comment]
The error should certainly be catched. It reminds me that Bob should catch plugin exceptions and print a proper error message that the plugin is faulty too.
